[package]
name = "nali"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
dirs = "5.0.1"
lazy_static = "1.5.0"
maxminddb = "0.24.0"
regex = "1.11.1"

[profile.release]
opt-level = 3
